# Usa imagem leve do Python com Alpine Linux
FROM python:3.13.4-alpine3.22

# Define o diretório de trabalho dentro do container
WORKDIR /app

# Copia arquivos do projeto para dentro do container
COPY requirements.txt .

# Instala dependências do sistema necessárias (ex: gcc, musl, libffi, etc)
RUN apk add --no-cache --virtual .build-deps \
        gcc musl-dev libffi-dev \
    && pip install --upgrade pip \
    && pip install -r requirements.txt \
    && apk del .build-deps

# Expõe a porta padrão do FastAPI/Uvicorn
EXPOSE 8000

# Comando padrão para rodar o app (ajuste se for diferente)
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
